name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Get packages
        run: flutter pub get

      - name: Run widget tests
        run: flutter test --machine > test-results.json

      - name: Show test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Flutter Test Results
          path: test-results.json
          reporter: flutter-json
          fail-on-error: true
        